/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as baseLayoutRouteImport } from './routes/(base)/_layout'
import { Route as authLayoutRouteImport } from './routes/(auth)/_layout'
import { Route as baseLayoutIndexRouteImport } from './routes/(base)/_layout.index'
import { Route as baseLayoutSearchRouteImport } from './routes/(base)/_layout.search'
import { Route as baseLayoutFavoritesRouteImport } from './routes/(base)/_layout.favorites'
import { Route as authLayoutSignupRouteImport } from './routes/(auth)/_layout.signup'
import { Route as authLayoutSigninRouteImport } from './routes/(auth)/_layout.signin'

const baseLayoutRoute = baseLayoutRouteImport.update({
  id: '/(base)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const baseLayoutIndexRoute = baseLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => baseLayoutRoute,
} as any)
const baseLayoutSearchRoute = baseLayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => baseLayoutRoute,
} as any)
const baseLayoutFavoritesRoute = baseLayoutFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => baseLayoutRoute,
} as any)
const authLayoutSignupRoute = authLayoutSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutSigninRoute = authLayoutSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/signin': typeof authLayoutSigninRoute
  '/signup': typeof authLayoutSignupRoute
  '/favorites': typeof baseLayoutFavoritesRoute
  '/search': typeof baseLayoutSearchRoute
  '/': typeof baseLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof authLayoutSigninRoute
  '/signup': typeof authLayoutSignupRoute
  '/favorites': typeof baseLayoutFavoritesRoute
  '/search': typeof baseLayoutSearchRoute
  '/': typeof baseLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/_layout': typeof authLayoutRouteWithChildren
  '/(base)/_layout': typeof baseLayoutRouteWithChildren
  '/(auth)/_layout/signin': typeof authLayoutSigninRoute
  '/(auth)/_layout/signup': typeof authLayoutSignupRoute
  '/(base)/_layout/favorites': typeof baseLayoutFavoritesRoute
  '/(base)/_layout/search': typeof baseLayoutSearchRoute
  '/(base)/_layout/': typeof baseLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/signin' | '/signup' | '/favorites' | '/search' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/signin' | '/signup' | '/favorites' | '/search' | '/'
  id:
    | '__root__'
    | '/(auth)/_layout'
    | '/(base)/_layout'
    | '/(auth)/_layout/signin'
    | '/(auth)/_layout/signup'
    | '/(base)/_layout/favorites'
    | '/(base)/_layout/search'
    | '/(base)/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
  baseLayoutRoute: typeof baseLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(base)/_layout': {
      id: '/(base)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof baseLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout': {
      id: '/(auth)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(base)/_layout/': {
      id: '/(base)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof baseLayoutIndexRouteImport
      parentRoute: typeof baseLayoutRoute
    }
    '/(base)/_layout/search': {
      id: '/(base)/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof baseLayoutSearchRouteImport
      parentRoute: typeof baseLayoutRoute
    }
    '/(base)/_layout/favorites': {
      id: '/(base)/_layout/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof baseLayoutFavoritesRouteImport
      parentRoute: typeof baseLayoutRoute
    }
    '/(auth)/_layout/signup': {
      id: '/(auth)/_layout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authLayoutSignupRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/signin': {
      id: '/(auth)/_layout/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authLayoutSigninRouteImport
      parentRoute: typeof authLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authLayoutSigninRoute: typeof authLayoutSigninRoute
  authLayoutSignupRoute: typeof authLayoutSignupRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authLayoutSigninRoute: authLayoutSigninRoute,
  authLayoutSignupRoute: authLayoutSignupRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface baseLayoutRouteChildren {
  baseLayoutFavoritesRoute: typeof baseLayoutFavoritesRoute
  baseLayoutSearchRoute: typeof baseLayoutSearchRoute
  baseLayoutIndexRoute: typeof baseLayoutIndexRoute
}

const baseLayoutRouteChildren: baseLayoutRouteChildren = {
  baseLayoutFavoritesRoute: baseLayoutFavoritesRoute,
  baseLayoutSearchRoute: baseLayoutSearchRoute,
  baseLayoutIndexRoute: baseLayoutIndexRoute,
}

const baseLayoutRouteWithChildren = baseLayoutRoute._addFileChildren(
  baseLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  baseLayoutRoute: baseLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
